#!/bin/sh
set -e

# Apache does not start, if PID directory is missing
[ -d /run/apache2 ] || mkdir -p /run/apache2

# Apache gets grumpy about PID files pre-existing
rm -f /run/apache2/httpd.pid

exec httpd -DFOREGROUND
